#!/bin/bash

quickdoc --discover ../../../projects/fileutils --html fileutils --interlink http://docs.python.org/2.7 --inheritance
quickdoc --discover ../../../projects/stm --html stm --interlink http://docs.python.org/2.7 --inheritance

